#NUMPY


class name of numpy is ndarray.

Numpy is a python library used for working with arrays.

In python we have lists that serves the purpose of arrays, but they are slow to process.

Numpy aims to provide an array object that is upto 50* faster than traditional python lists.

The array object in numpy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science , where speed and resources are very important.

Collection of homogenous data.

Size is fixed.

numpy is a.



In [ ]:
import numpy as np


In [1]:
import numpy as np

x = np.ndarray([2,3,6,1])

print(x)


[[[[1.        ]
   [1.        ]
   [0.8       ]
   [1.        ]
   [1.        ]
   [0.92941176]]

  [[0.62745098]
   [1.        ]
   [0.99607843]
   [0.85098039]
   [0.4627451 ]
   [1.        ]]

  [[0.99607843]
   [0.69803922]
   [0.29803922]
   [1.        ]
   [0.99215686]
   [0.55294118]]]


 [[[0.23529412]
   [1.        ]
   [0.98823529]
   [0.30588235]
   [0.16470588]
   [1.        ]]

  [[0.89019608]
   [0.10196078]
   [0.10980392]
   [1.        ]
   [0.74117647]
   [0.        ]]

  [[0.14901961]
   [1.        ]
   [0.50196078]
   [0.        ]
   [0.14901961]
   [1.        ]]]]


In [2]:
import numpy as np

x = np.array([1,3,4,6])
print(x)

[1 3 4 6]


In [3]:
print(type(x))


<class 'numpy.ndarray'>


In [4]:
print(x.ndim)


1


In [5]:
print(x.shape)


(4,)


In [6]:
import numpy as np

x = np.array([[1,2,3,4],[8,5,6,7]])

print(x)
print(x.shape)
print(x.ndim)


[[1 2 3 4]
 [8 5 6 7]]
(2, 4)
2


In [7]:
import numpy as np

a = np.array([[1,2,3,4,55],[5,6,7,8,56],[9,10,11,12,57],[13,14,15,16,23]])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4 55]
 [ 5  6  7  8 56]
 [ 9 10 11 12 57]
 [13 14 15 16 23]]
(4, 5)
2


In [8]:
import numpy as np

b = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
2


In [ ]:
#1D - single axis - x
#2D - Two axis - x,y
#3D - Three axis - x,y,z


In [9]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)
3


In [10]:
import numpy as np

array_1 = np.array([[[1,2],[3,4],[5,6],[7,8]],[[11,12],[13,14],[15,16],[17,18]]])

array_2 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[66,34,67]],[[22,68,90],[34,94,27]]])

array_3 = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]],
                    [[11,12],[34,28]],
                    [[67,45],[34,78]]])

print(array_1)
print(array_1.shape)
print(array_1.ndim)
print(array_2)
print(array_2.shape)
print(array_2.ndim)
print(array_3)
print(array_3.shape)
print(array_3.ndim)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]]]
(2, 4, 2)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [66 34 67]]

 [[22 68 90]
  [34 94 27]]]
(3, 2, 3)
3
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 12]
  [34 28]]

 [[67 45]
  [34 78]]]
(4, 2, 2)
3


In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((2,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
np.ones((2,3,4),dtype = int)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [14]:
np.arange(20,80,5)


array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [15]:
np.linspace(20,80,8)


array([20.        , 28.57142857, 37.14285714, 45.71428571, 54.28571429,
       62.85714286, 71.42857143, 80.        ])

In [16]:
np.linspace(20,80)


array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [17]:
np.full((3,4),70,dtype = float)


array([[70., 70., 70., 70.],
       [70., 70., 70., 70.],
       [70., 70., 70., 70.]])

In [18]:
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.random((2,3,2))


array([[[0.32778004, 0.60764597],
        [0.34248455, 0.49360184],
        [0.51539302, 0.61211462]],

       [[0.40199036, 0.74213532],
        [0.03089974, 0.72065618],
        [0.99961357, 0.44039542]]])

In [20]:
np.random.randint(100,200,(3,2,2))


array([[[186, 191],
        [121, 173]],

       [[104, 170],
        [161, 136]],

       [[110, 159],
        [131, 155]]])

In [21]:
np.random.randint(100,size=(3,2,3))


array([[[80,  4, 84],
        [70, 15, 68]],

       [[51, 17,  0],
        [25, 96, 23]],

       [[45, 30, 29],
        [71, 84, 84]]])

In [22]:
a = np.array([[10,23,11],[5,7,8]])

b= np.array([[9,11,22],[12,33,67]])

print(a)
print(b)


[[10 23 11]
 [ 5  7  8]]
[[ 9 11 22]
 [12 33 67]]


In [23]:
# ADD

np.add(a,b)

array([[19, 34, 33],
       [17, 40, 75]])

In [24]:
# SUBTRACT

np.subtract(a,b)


array([[  1,  12, -11],
       [ -7, -26, -59]])

In [25]:
# MULTIPLY

np.multiply(a,b)


array([[ 90, 253, 242],
       [ 60, 231, 536]])

In [26]:
# DIVIDE

np.divide(a,b)


array([[1.11111111, 2.09090909, 0.5       ],
       [0.41666667, 0.21212121, 0.11940299]])

In [27]:
# POWER

np.power(a,b)

array([[          1000000000,      952809757913927, -2732210440490168087],
       [           244140625,  5883222197588761863,                    0]])